### ISSUE TITLE
Error on display

### ISSUE THREAD

**Issue by AdamSLevy** [szym/display#2]
When I run and load the page all I see is a grey screen with the word Error in a small red rectangle in the upper right.

The console displays this every time I run and then refresh the http://localhost:8000/ page:

```
$ ~/.display/run.js &
[1] 38756
$ Listening on http://undefined:8000
RangeError: msecs must be a non-negative finite number
at Object.exports.enroll (timers.js:160:11)
at Socket.setTimeout (net.js:329:12)
at /Users/adamlevy/.display/server.js:14:16
at Layer.handle [as handle_request] (/Users/adamlevy/.display/node_modules/express/lib/router/layer.js:82:5)
at next (/Users/adamlevy/.display/node_modules/express/lib/router/route.js:110:13)
at Route.dispatch (/Users/adamlevy/.display/node_modules/express/lib/router/route.js:91:3)
at Layer.handle [as handle_request] (/Users/adamlevy/.display/node_modules/express/lib/router/layer.js:82:5)
at /Users/adamlevy/.display/node_modules/express/lib/router/index.js:267:22
at Function.proto.process_params (/Users/adamlevy/.display/node_modules/express/lib/router/index.js:321:12)
at next (/Users/adamlevy/.display/node_modules/express/lib/router/index.js:261:10)
```

**Comment by szym** [comment]
Thanks for the report. This seems like a problem caused after this commit to node: https://github.com/joyent/node/commit/f34757398fcc393685b4dfbcbdc692fb38332d6c

77ab8d07a987a280be83481e5aaaf105070902d9 reduces the timeout from Infinity to just really-large.

**Comment by AdamSLevy** [comment]
Can I do anything about that?

**Comment by szym** [comment]
This should be fixed already. Let me know if you are still having trouble after pulling.

**Comment by AdamSLevy** [comment]
Fixed. Thank you.
